config/routes.rb
Rails.application.routes.draw do

  root to: "reports#index"

  get 'site/index'

  # User routes

  resources :users

  # Sessions routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  post 'reports/:id/hide', to: "reports#hide", as: 'hide_report'
  post 'reports/:id/confirm', to: "reports#confirm", as: 'confirm_report'
  resources :reports
  resources :confirmed_issues

end

app/models/confirmed_issue.rb
class ConfirmedIssue < ActiveRecord::Base
  has_and_belongs_to_many :reports

  enum category: ["Pothole", "Sidewalk", "Streetlight", "Traffic Signal", "Signage",
                  "Road Obstruction", "Pavement", "Powerline", "Vandalism", "Animal Control",
                  "Other"]
  enum status: [:pending, :in_progress, :closed, :hidden]
  enum danger_level: ["Mild", "Moderate", "Severe"]
end

app/controllers/confirmed_issues_controller.rb
class ConfirmedIssuesController < ApplicationController
  before_action :new_report
  before_action :authorize, only: [:edit, :update]
  before_action :set_confirmed_issue

  def index
    @confirmed_issue = ConfirmedIssue.new
    @confirmed_issues = ConfirmedIssue.all

    @hash = Gmaps4rails.build_markers(@confirmed_issues) do |issue, marker|
      issue_path = view_context.link_to "View Details", confirmed_issue_path(issue), :"data-no-turbolink" => true
      marker.lat issue.latitude
      marker.lng issue.longitude
      marker.infowindow "<b>Issue ##{issue.id}</b><br>
                        #{issue.title}<br>
                        Category: #{issue.category}<br>
                        #{issue_path}<br>"
    end
  end

  def show
    reports = @confirmed_issue.reports
    @hash = Gmaps4rails.build_markers(reports) do |issue, marker|
      issue_path = view_context.link_to "View Details", confirmed_issue_path(issue), :"data-no-turbolink" => true
      marker.lat issue.latitude
      marker.lng issue.longitude
      marker.infowindow "<b>Issue ##{issue.id}</b><br>
                        #{issue.title}<br>
                        Category: #{issue.category}<br>
                        #{issue_path}<br>"
    end
  end

  def new
    @confirmed_issue = ConfirmedIssue.new
  end

  def edit

    ci_report = @confirmed_issue.reports[0]
    distance = 0.1
    center_point = [ci_report.latitude, ci_report.longitude]
    box = Geocoder::Calculations.bounding_box(center_point, distance)
    near_reports = Report.within_bounding_box(box)

    @similar_reports = []
    near_reports.each do |report|
      if ci_report.id != report.id
        @similar_reports << report
      end
    end

  end

  def update
    @confirmed_issue.update(confirmed_issue_params)

    if !params[:confirmed_issue][:id].blank?

      # filter through reports id array in params
      params[:confirmed_issue][:id].each do |id|
        if !id.blank?
          # find reports by id's in array
          report = Report.find(id.to_i)

          # push reports into confirmed_issue
          # hacky but it works :/
          @confirmed_issue.reports << report

          # updates each report status to confirmed
          @confirmed_issue.reports.each do |report|
            report.status = :confirmed
            report.confirmed!
          end
        end
      end
    end

    redirect_to confirmed_issue_path
  end

  private

  def confirmed_issue_params
    params.require(:confirmed_issue)
          .permit(:title, :latitude, :longitude,
                  :category, :major_road,
                  :cross_street1, :cross_street2,
                  :danger_level, :status, :notes)
  end

  def set_confirmed_issue
    @confirmed_issue = ConfirmedIssue.find_by_id(params[:id])
  end

  def new_report
    # set report for report an issue button
    @report = Report.new
  end
end

app/helpers/confirmed_issues_helper.rb
module ConfirmedIssuesHelper
end

app/views/confirmed_issues/_form.html.erb
    <%= form_for @confirmed_issue do |f| %>
      <div class="row">
        <div class="s12">
          <%= f.label :title %>
          <%= f.text_field :title,required: true %>
        </div>
      </div>


      <div class="row">
        <div class="col s3">
          <%= f.label :category %>
          <%= f.select(:category, ["Pothole", "Sidewalk", "Streetlight", "Traffic Signal", "Signage",
                          "Road Obstruction", "Pavement", "Powerline", "Vandalism", "Animal Control",
                          "Other"], {}, {:class => "browser-default"})%>
        </div>
        <div class="col s3">
          <%= f.label :danger_level %>
          <%= f.select(:danger_level, ["Mild", "Moderate", "Severe"], {}, {:class => "browser-default"})%>
        </div>
        <div class="col s3">
          <%= f.label :status %>
          <%= f.select(:status, [:pending, :in_progress, :closed, :hidden], {}, {:class => "browser-default"})%>
        </div>
      </div>

      <div class="row">
        <div class="s12">
          <%= f.label :notes %>
          <%= f.text_area :notes %>
        </div>
      </div>

    <% if !@similar_reports.blank? %>
      <div class="row">
        <div class="edit-select">
          <%= f.label :add_similar_reports %>
          <%= f.collection_check_boxes :id, @similar_reports, :id, :report_with_id do |b| %>
            <div class="collection_check_box">
              <%= b.check_box %>
              <%= b.label %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>


  <%= f.submit "Submit", class: "modal-action modal-close btn waves-effect waves-light"%>
<% end %>

app/views/confirmed_issues/edit.html.erb
<div class="row">
  <div class="col s10 offset-s1">
    <h3>Edit Issue Details</h3>

    <%= render "form" %>

  </div>
</div>

app/views/confirmed_issues/index.html.erb
<div class="row">
  <div class="col s3 sidebar">
    <h5>All Confirmed Issues</h5>
    <% @confirmed_issues.each do |issue| %>
      <b>Issue #<%= issue.id %></b> <br>
      <%= link_to issue.title, confirmed_issue_path(issue) %> <br><br>
    <% end %>
  </div>
  <div class="col s9">
      <div class="fixed-action-btn" style="top: 70px; right: 24px; z-index: 3">
        <a class="modal-trigger waves-effect waves-light red btn"
           href="#report-modal">Make a Report</a>
      </div>
    <%= render "reports/map" %>
  </div>
</div>


<%= render "reports/modal" %>

app/views/confirmed_issues/new.html.erb
<h3>New Confirmed Issue</h3>

<%= render 'form' %>

app/views/confirmed_issues/show.html.erb
<div class="row">
  <div class="col s3 sidebar">
    <% if current_user && current_user.admin? %>
      <%= link_to edit_confirmed_issue_path(@confirmed_issue),
        method: :get,
        class: "btn-floating btn-medium waves-effect waves-light btn right" do %>
        <i class="material-icons">mode_edit</i>
      <% end %>
    <% end %>

    <h4 class="teal-text text-accent-4">Issue #<%= @confirmed_issue.id %></h4>
    <span class="flow-text">
      <strong>Status: </strong>  <%= @confirmed_issue.status %>
    </span>
    <p>
      <strong>Title: </strong>  <%= @confirmed_issue.title %> <br>
      <strong>Notes: </strong>  <%= @confirmed_issue.notes %> <br>
      <strong>Category: </strong>  <%= @confirmed_issue.category %> <br>
      <strong>Danger Level: </strong>  <%= @confirmed_issue.danger_level %> <br>


      <strong>Reports: </strong>
      <ol>
        <% @confirmed_issue.reports.each do |report| %>
            <li> <%= link_to "Report ##{report.id}", report_path(report) %> </li>
        <% end %>
      </ol>
    </p>
  </div>

  <div class="col s9">
    <%= render "reports/map" %>
  </div>
</div>