config/routes.rb
Rails.application.routes.draw do

  root to: "reports#index"

  get 'site/index'

  # User routes

  resources :users

  # Sessions routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  post 'reports/:id/hide', to: "reports#hide", as: 'hide_report'
  post 'reports/:id/confirm', to: "reports#confirm", as: 'confirm_report'
  resources :reports
  resources :confirmed_issues

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_and_belongs_to_many :confirmed_issues

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  enum category: ["Pothole", "Sidewalk", "Streetlight", "Traffic Signal", "Signage",
                  "Road Obstruction", "Pavement", "Powerline", "Vandalism", "Animal Control",
                  "Other"]
  enum status: [:active, :confirmed, :flagged, :deleted, :hidden]
  enum danger_level: ["Mild", "Moderate", "Severe"]

  def report_with_id
    "Report ##{id}"
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authorize, only: [:edit, :update, :confirm]

  def index

    @report = Report.new
    @reports = Report.all
    @hash = Gmaps4rails.build_markers(@reports) do |report, marker|
      if !report.hidden?
        report_path = view_context.link_to "View Details", report_path(report), :"data-no-turbolink" => true
        marker.lat report.latitude
        marker.lng report.longitude
        marker.infowindow "<b>Report ##{report.id}</b><br>
                          #{report.title}<br>
                          Category: #{report.category}<br>
                          #{report.address}<br>
                          #{report_path}<br>"
      end
    end
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to report_path(@report)
    end
  end

  def show
    @report = Report.find_by_id(params[:id])
    if !@report.hidden?
      return map_related_reports(@report)
    else
      if !current_user || !current_user.admin?
        flash[:alert] = "That report has been removed."
        return redirect_to reports_path
      elsif current_user.admin?
        map_related_reports(@report)
      end
    end
  end

  def edit
    @report = Report.find_by_id(params[:id])
  end

  def update
    @report = Report.find_by_id(params[:id])
    if @report.update(report_params)
      flash[:notice] = "Report has been successfully updated"
      redirect_to report_path(@report)
    else
      flash[:error] = @report.errors.full_messages.join(", ")
      redirect_to edit_report_path(@report)
    end
  end

  def map_related_reports(report)
    distance = 0.1
    center_point = [report.latitude, report.longitude]
    box = Geocoder::Calculations.bounding_box(center_point, distance)
    @related_reports = Report.within_bounding_box(box)

    @hash = Gmaps4rails.build_markers(@related_reports) do |report, marker|
      report_path = view_context.link_to "View Details", report_path(report), :"data-no-turbolink" => true
      marker.lat report.latitude
      marker.lng report.longitude
      marker.infowindow "<b>Report ##{report.id}</b><br>
                        #{report.title}<br>
                        Category: #{report.category}<br>
                        #{report.address}<br>
                        #{report_path}<br>"
    end
  end

  # POST reports/:id/confirm # creates a new confirmed issue
  def confirm
    @report = Report.find_by_id(params[:id])

    #changes status to confirmed
    @report.status = :confirmed

    #updates the report
    @report.confirmed!

    #create a new confirmed issue record with inherited attributes from report
    ci = @report.confirmed_issues.create(confirmed_issue_params(@report))

    #redirect to edit confirmed issue form with ci data
    return redirect_to edit_confirmed_issue_path(ci)
  end

  def hide
    @report = Report.find_by_id(params[:id])

    @report.status = :hidden
    @report.hidden!

    redirect_to reports_path
  end

  private

  def confirmed_issue_params(report)
    confirmed_issue_params = {
      title: report.title,
      category: report.category,
      danger_level: report.danger_level,
      major_road: report.major_road,
      cross_street1: report.cross_street1,
      cross_street2: report.cross_street2,
      latitude: report.latitude,
      longitude: report.longitude
      }

  end

  def report_params
    params.require(:report).permit(:title, :latitude, :longitude, :description,
                                   :category, :major_road, :address, :status,
                                   :cross_street1, :cross_street2, :danger_level)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for @report do |f| %>
<div class="row">
  <div class="s12">
    <%= f.label :address %>
    <%= f.text_field :address,required: true %>
  </div>
</div>
<div class="row">
  <div class="s12">
    <%= f.label :title %>
    <%= f.text_field :title,required: true %>
  </div>
</div>

<div class="row">
  <div class="s12">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
</div>
<div class="row">
  <div class="col s4">
    <%= f.label :category %>
    <%= f.select(:category, ["Pothole", "Sidewalk", "Streetlight", "Traffic Signal", "Signage",
                    "Road Obstruction", "Pavement", "Powerline", "Vandalism", "Animal Control",
                    "Other"], {}, {:class => "browser-default"})%>
  </div>
  <div class="col s4">
    <%= f.label :danger_level %>
    <%= f.select(:danger_level, ["Mild", "Moderate", "Severe"], {}, {:class => "browser-default"})%>
  </div>
  <% if current_user && current_user.admin? %>
  <div class="col s4">
    <%= f.label :status %>
    <%= f.select(:status, [:active, :confirmed, :flagged, :hidden], {}, {:class => "browser-default"})%>
  </div>
  <% end %>

</div>
<div class="s6">
<%= f.submit "Submit", class: "btn waves-effect waves-light"%>
</div>



<% end %>

app/views/reports/_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyATl1C376VZ4AGorIBLCyTTdc-19GynoJw"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>


<!-- Map -->




 <div id="map"></div>



<script>
  window.data_hash = <%=raw @hash.to_json %> || null;
</script>

app/views/reports/_modal.html.erb
<!-- Modal Structure -->
<div id="report-modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Report an Issue</h4>
    <%= render "reports/form" %>
  </div>
  <div class="modal-footer">
    <a href="#!" data-no-turbolink="true" class="modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
  </div>
</div>

app/views/reports/edit.html.erb
<div class="row">
  <div class="col s8 offset-s2">
    <h4>Edit Report Details</h4>
    <%= render 'form' %>
  </div>
</div>

app/views/reports/index.html.erb
<div class="row">
  <div class="col s3 sidebar">
    <h5>All User Reports</h5>

    <!-- logic to hide reports to non-users and users that are not admins -->
    <% if !current_user || !current_user.admin? %>
      <% @reports.each do |report| %>
        <% if !report.hidden? %>
          <div class="chip <% if report.status=="flagged" || report.status=="hidden"%>
                      red <% elsif report.status=="confirmed" %> teal accent-3<%else %>
                      indigo accent-2 <% end %> right">
              <span class="white-text"><%= report.status %></span>
            </div>
            <div class="">
              <b>Report #<%= report.id %></b> <br>
              <%= link_to report.title, report_path(report) %> <br>
            </div><br><br>
          <% end %>
        <% end %>

    <% elsif current_user.admin? %>

      <% @reports.each do |report| %>
        <div class="chip <% if report.status=="flagged" || report.status=="hidden"%>
                    red <% elsif report.status=="confirmed" %> green lighten-1 <%else %>
                    indigo accent-2 <% end %> right">
          <span class="white-text"><%= report.status %></span>
        </div>
        <div class="">
          <b>Report #<%= report.id %></b> <br>
          <%= link_to report.title, report_path(report) %> <br>
        </div>

        <br><br>
      <% end %>
    <% end %>
    <!-- end of hide report logic -->

  </div>
  <div class="col s9">
    <div class="fixed-action-btn" style="top: 70px; right: 24px; z-index: 3">
      <a class="modal-trigger waves-effect waves-light red btn"
         href="#report-modal">Make a Report</a>
    </div>
    <%= render "map" %>
  </div>
</div>

<%= render "modal" %>

app/views/reports/related.html.erb
<%= @reports %>
<br>
<%= @all_centers %>

app/views/reports/show.html.erb
<div class="row">
  <div class="col s3">
    <% if current_user && current_user.admin? %>
      <%= button_to edit_report_path(@report),
          method: :get,
          class: "btn-floating btn-medium waves-effect waves-light btn right" do %>
          <i class="material-icons">mode_edit</i>
      <% end %>
    <% end %>

    <h4 class="red-text">Report #<%= @report.id %></h4>
    <span class="flow-text">  <strong>Status: </strong>  <%= @report.status %>
          <% if @report.confirmed? %>
            <i class="small material-icons green-text">done</i>
          <% end %>
    </span>
    <br>
    <p>
      <strong>Title: </strong>  <%= @report.title %> <br>
      <strong>Description: </strong>  <%= @report.description %> <br>
      <strong>Category: </strong>  <%= @report.category %> <br>
      <strong>Danger Level: </strong>  <%= @report.danger_level%> <br>
      <strong>Upvotes: </strong> <%= @report.upvotes %> <br>
      <strong>Downvotes: </strong> <%= @report.downvotes %> <br>
    </p>
    <div class="">
      <span class="flow-text">
        <strong>Similar Reports:</strong><br>
      </span>

      <!-- If there are no other reports within proximity beside the report itself -->
      <% if @related_reports.length == 1 %>
        <p>No similar reports found. </p>
      <% end %>

      <!-- If there are reports in proximity display them here -->
      <% @related_reports.each do |report| %>
         <% if report.id != @report.id %>
           <%= link_to "Report ##{report.id}", report_path(report) %> <br>
         <% end %>
      <% end %>
    </div>

    <!-- button to confirm report -->
    <% if !@report.confirmed? && current_user && current_user.admin? %>
      <%= button_to confirm_report_path(@report),
          :action => "confirm",
          class: "waves-effect waves-light btn" do %>
          Confirm Report #<%= @report.id %>
      <% end %>
    <% end %>

    <!-- button to hide report -->
    <% if !@report.hidden? && current_user && current_user.admin? %>
      <%= button_to hide_report_path(@report),
          :action => "hide",
          class: "waves-effect waves-light btn red" do %>
          Hide Report #<%= @report.id %>
      <% end %>
    <% end %>

  </div>

  <div class="col s9">
    <%= render "reports/map" %>
  </div>

</div>