config/routes.rb
Rails.application.routes.draw do

  root to: "reports#index"

  get 'site/index'

  # User routes

  resources :users

  # Sessions routes
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  post 'reports/:id/hide', to: "reports#hide", as: 'hide_report'
  post 'reports/:id/confirm', to: "reports#confirm", as: 'confirm_report'
  resources :reports
  resources :confirmed_issues

end

app/views/layouts/_navbar.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li> <%= link_to "All User Reports", reports_path %> </li>
  <li class="divider"></li>
  <li> <%= link_to "Confirmed Issues", confirmed_issues_path %> </li>
</ul>
<nav>
  <div class="nav-wrapper blue-grey lighten-1">
    <a href="/reports" class="brand-logo">Fix My City</a>
    <ul class="right hide-on-small-and-down">
      <li>
        <% flash.each do |name, msg| %>
          <div class="chip <% if name=="error" || name=="alert" %> red <% else %> green lighten-1 <% end %>">
            <span class="white-text"><%=  msg %></span>
            <i class="material-icons">close</i>
          </div>
        <% end %>
      </li>
      <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Reports<i class="material-icons right">arrow_drop_down</i></a></li>

      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user)  %></li>
        <li><%= link_to "Log Out", logout_path  %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_path  %></li>
        <li><%= link_to "Log In", login_path  %></li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fix My City</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  <%= render "layouts/navbar" %>

  <%= yield %>
</body>
</html>